### ISSUE TITLE
Launch Android Emulator doesn't work

### ISSUE THREAD

**Issue by RedMickey** [Samriel/issueTraining#1]
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

 Brand new project, I open in VSCode (Insiders) win 10 press F1, Launch Android Emulator

## Expected behavior 

What were you expecting to happen? 
An Android emulator opens  i.e. Nexus_5X_API_29 which is the only one in my  AVD mangement list.
OR am I misunderstanding what this does?

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console) Nothing

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

[Error] An error occurred while starting the Android emulator (error code 305)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project: Win 10,  21H1, VS Code insiders. latest everything.

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```
all clear
* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: latest
* Expo SDK version (if applicable): VERSION

**Comment by Samriel** [comment]
Hello. Could you please provide us with:
> debug console info
> results of `npx envinfo`
> logs of debug console
for us to be able to further investigate this issue.

**Comment by RedMickey** [comment]
Here is the commands outputs:

- `emulator -list-avds`

```
> emulator -list-avds
Nexus_5X_API_29
```

- `emulator -avd Nexus_5X_API_29`

```
> emulator -avd Nexus_5X_API_29
PANIC: Missing emulator engine program for 'x86' CPU.
```

**Comment by Samriel** [comment]
@RedMickey, please, check your emulator path variable. In new versions of android studio the path should be:
`/<xxx>/Android/sdk/tools/emulator/emulator`

**Comment by RedMickey** [comment]
@Samriel Oh, it seems that the `emulator` command was missed in my Path. I added it to the Path, but it looks like the problem remains. The emulator launching command still fails with the same error.
![image](https://user-images.githubusercontent.com/33267199/152535966-5a1b0819-c91a-478a-857e-d0ba89ed73ca.png)
Could it be that I'm missing something?

**Comment by Samriel** [comment]
@RedMickey, could you please move `%ANDROID_HOME%\emulator` over `%ANDROID_HOME%\tools`. This is necessary, because path variables are being checked consequently until system reaches required utility. tools folder contains "emulator" as well, but the one you need is located in "emulator" folder.

**Comment by RedMickey** [comment]
Now it's working. Thanks!
